"""empty message

Revision ID: 490feaedd11c
Revises: 
Create Date: 2018-03-01 16:13:10.073567

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '490feaedd11c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('main_ingredient',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=250), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dish',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=250), nullable=False),
    sa.Column('is_breakfast', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=250), nullable=True),
    sa.Column('cooking_time', sa.String(length=30), nullable=True),
    sa.Column('recipe_link', sa.String(length=100), nullable=False),
    sa.Column('main_ingredient_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['main_ingredient_id'], ['main_ingredient.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dish')
    op.drop_table('main_ingredient')
    # ### end Alembic commands ###
